### ISSUE TITLE
Cannot build on mac os BigSur

### ISSUE THREAD

**Issue by hey-johnnypark** [iris-gateway/eps#1]
When I run make I get:

```
→ make
# github.com/kiprotect/go-helpers/forms
../../../../go/pkg/mod/github.com/kiprotect/go-helpers@v0.0.0-20210501184624-677c272d4158/forms/coerce.go:207:25: targetFieldValue.IsZero undefined (type reflect.Value has no field or method IsZero)
make: *** [dep] Error 2
```

Any idea? :) Thank you.

**Comment by adewes** [comment]
Which Go version are you on? Maybe a problem with the `reflect` package used by the form serializer. I'll bump up the Go version in `go.mod` as well, seems I was too generous with the required version.

**Comment by hey-johnnypark** [comment]
@adewes 

```
→ go version

go version go1.12.7 darwin/amd64
```

**Comment by adewes** [comment]
It seems indeed that we need Golang 1.13 for this (https://golang.org/doc/go1.13). The `go.mod` is saying Golang 1.12 in the `kiprotect/go-helpers` repository, so I'll update it there as well.

Upgrading to `>=1.13` should solve this issue.

**Comment by hey-johnnypark** [comment]
```
→ brew upgrade go
Warning: go 1.16.3 already installed
```

Solved the problem. Danke @adewes
